// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAebv5lEF4Y8OWTJygjsZH20ACvgUIGEm4',
    appId: '1:223252582503:web:a902c33e75394fbbe844c2',
    messagingSenderId: '223252582503',
    projectId: 'machine-test-d5158',
    authDomain: 'machine-test-d5158.firebaseapp.com',
    storageBucket: 'machine-test-d5158.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUmoDxKhhI0gjPHae9-gZJXncWtype7uM',
    appId: '1:223252582503:android:b5706eb5364234b0e844c2',
    messagingSenderId: '223252582503',
    projectId: 'machine-test-d5158',
    storageBucket: 'machine-test-d5158.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9GwpDdZJWCfyj5M9jDJd96kK7d1sz5W0',
    appId: '1:223252582503:ios:ed44a7551ff17face844c2',
    messagingSenderId: '223252582503',
    projectId: 'machine-test-d5158',
    storageBucket: 'machine-test-d5158.firebasestorage.app',
    iosBundleId: 'com.example.machineTest',
  );
}
